"""Relation owner and business modified

Revision ID: 11c657c85c97
Revises: deb39e718211
Create Date: 2025-01-20 16:18:12.129882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11c657c85c97'
down_revision = 'deb39e718211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('duenio_establecimiento')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duenio_establecimiento',
    sa.Column('id_establecimiento', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_duenio', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_duenio'], ['duenio.id_duenio'], name='duenio_establecimiento_id_duenio_fkey'),
    sa.ForeignKeyConstraint(['id_establecimiento'], ['establecimiento.id_establecimiento'], name='duenio_establecimiento_id_establecimiento_fkey'),
    sa.PrimaryKeyConstraint('id_establecimiento', 'id_duenio', name='duenio_establecimiento_pkey')
    )
    # ### end Alembic commands ###
