"""Referencia pago y reservas host

Revision ID: 13ecea267950
Revises: 986cfc72470a
Create Date: 2025-02-18 09:34:55.212602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13ecea267950'
down_revision = '986cfc72470a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_referencia_pago', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('id_host', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('id_duenio', 'duenio', ['id_host'], ['id_duenio'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.drop_constraint('id_duenio', type_='foreignkey')
        batch_op.drop_column('id_host')
        batch_op.drop_column('id_referencia_pago')

    # ### end Alembic commands ###
