"""Reservante in reserva optional for owners

Revision ID: 148607a766f4
Revises: 45e6d535e8ba
Create Date: 2025-02-22 00:03:05.717620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '148607a766f4'
down_revision = '45e6d535e8ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.alter_column('id_reservante',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.alter_column('id_reservante',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
