"""Particpante table created

Revision ID: 2b7ea250219f
Revises: 5881a3ffcc16
Create Date: 2025-01-23 12:32:34.427682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b7ea250219f'
down_revision = '5881a3ffcc16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('duenio_establecimiento')
    with op.batch_alter_table('establecimiento', schema=None) as batch_op:
        batch_op.alter_column('localidad',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    with op.batch_alter_table('horario_cancha', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cancha', type_='foreignkey')
        batch_op.drop_constraint('fk_horario', type_='foreignkey')
        batch_op.create_foreign_key(None, 'horario', ['id_horario'], ['id_horario'])
        batch_op.create_foreign_key(None, 'cancha', ['id_cancha'], ['id_cancha'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horario_cancha', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_horario', 'horario', ['id_horario'], ['id_horario'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_cancha', 'cancha', ['id_cancha'], ['id_cancha'], ondelete='CASCADE')

    with op.batch_alter_table('establecimiento', schema=None) as batch_op:
        batch_op.alter_column('localidad',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    op.create_table('duenio_establecimiento',
    sa.Column('id_establecimiento', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_duenio', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_duenio'], ['duenio.id_duenio'], name='duenio_establecimiento_id_duenio_fkey'),
    sa.ForeignKeyConstraint(['id_establecimiento'], ['establecimiento.id_establecimiento'], name='duenio_establecimiento_id_establecimiento_fkey'),
    sa.PrimaryKeyConstraint('id_establecimiento', 'id_duenio', name='duenio_establecimiento_pkey')
    )
    # ### end Alembic commands ###
