"""imagen en equipo

Revision ID: 2c0e4090a053
Revises: f77a76d44b7e
Create Date: 2025-01-30 20:28:45.169371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c0e4090a053'
down_revision = 'f77a76d44b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participante')
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('descripcion', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.drop_column('descripcion')
        batch_op.drop_column('imagen')

    op.create_table('participante',
    sa.Column('id_participante', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_equipo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_equipo'], ['equipo.id_equipo'], name='id_equipo'),
    sa.PrimaryKeyConstraint('id_participante', name='participante_pkey')
    )
    # ### end Alembic commands ###
