"""Update migratons new

Revision ID: 3597f8f3cff5
Revises: ef03608bbff2
Create Date: 2025-01-14 12:14:44.829949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3597f8f3cff5'
down_revision = 'ef03608bbff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('horario_cancha')
    with op.batch_alter_table('cancha', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=sa.TEXT(),
               type_=sa.String(length=80),
               existing_nullable=False)

    with op.batch_alter_table('horario', schema=None) as batch_op:
        batch_op.alter_column('hora_inicio',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.Time(),
               existing_nullable=False,
               postgresql_using='hora_inicio::time without time zone')
        batch_op.alter_column('hora_fin',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.Time(),
               existing_nullable=False,
               postgresql_using='hora_fin::time without time zone')

    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.alter_column('rut',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.alter_column('rut',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    with op.batch_alter_table('horario', schema=None) as batch_op:
        batch_op.alter_column('hora_fin',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.alter_column('hora_inicio',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    with op.batch_alter_table('cancha', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=sa.String(length=80),
               type_=sa.TEXT(),
               existing_nullable=False)

    op.create_table('horario_cancha',
    sa.Column('id_horario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_cancha', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_cancha'], ['cancha.id_cancha'], name='fk_cancha', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_horario'], ['horario.id_horario'], name='fk_horario', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_horario', 'id_cancha', name='horario_cancha_pkey')
    )
    # ### end Alembic commands ###
