"""actualizacion establecimiento y duenio

Revision ID: 52dbf20fc9f3
Revises: 6674074fdb25
Create Date: 2025-02-01 21:21:40.710771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52dbf20fc9f3'
down_revision = '6674074fdb25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('duenio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_doc', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('documento', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fecha_nacimiento', sa.DateTime(), nullable=True))

    with op.batch_alter_table('establecimiento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('telefono', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('establecimiento', schema=None) as batch_op:
        batch_op.drop_column('telefono')
        batch_op.drop_column('direccion')

    with op.batch_alter_table('duenio', schema=None) as batch_op:
        batch_op.drop_column('fecha_nacimiento')
        batch_op.drop_column('documento')
        batch_op.drop_column('tipo_doc')

    # ### end Alembic commands ###
