"""Update migratons noti

Revision ID: 54eac4cc210c
Revises: 
Create Date: 2025-01-12 01:06:07.695848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54eac4cc210c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacion_estadistica', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_capitan', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('id_partido', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('capitan', 'usuario', ['id_capitan'], ['id_usuario'])
        batch_op.create_foreign_key('partido', 'partido', ['id_partido'], ['id_partido'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacion_estadistica', schema=None) as batch_op:
        batch_op.drop_constraint('partido', type_='foreignkey')
        batch_op.drop_constraint('capitan', type_='foreignkey')
        batch_op.drop_column('id_partido')
        batch_op.drop_column('id_capitan')

    # ### end Alembic commands ###
