"""Datetime type en reservas

Revision ID: 64fa2e4ceee0
Revises: 69126173756d
Create Date: 2025-02-03 01:14:38.321544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64fa2e4ceee0'
down_revision = '69126173756d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.alter_column('hora_inicio',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.DateTime(timezone=False),
               existing_nullable=False,
               postgresql_using='hora_inicio::timestamp without time zone')
        batch_op.alter_column('hora_fin',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.DateTime(timezone=False),
               existing_nullable=False,
               postgresql_using='hora_fin::timestamp without time zone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.alter_column('hora_fin',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.alter_column('hora_inicio',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
