"""relacion entre reservante-usuario-equipo

Revision ID: 6674074fdb25
Revises: 2c0e4090a053
Create Date: 2025-02-01 21:12:56.307819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6674074fdb25'
down_revision = '2c0e4090a053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_equipo_reservante', 'reservante', ['id_equipo'], ['id_reservante'])

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_usuario_reservante', 'reservante', ['id_usuario'], ['id_reservante'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint('fk_usuario_reservante', type_='foreignkey')

    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.drop_constraint('fk_equipo_reservante', type_='foreignkey')

    # ### end Alembic commands ###
