"""Estado pago agregado

Revision ID: 69126173756d
Revises: 52dbf20fc9f3
Create Date: 2025-02-02 20:09:54.610880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69126173756d'
down_revision = '52dbf20fc9f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('duenio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', sa.String(length=80), nullable=True))

    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado_procesado', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.drop_column('estado_procesado')

    with op.batch_alter_table('duenio', schema=None) as batch_op:
        batch_op.drop_column('telefono')

    # ### end Alembic commands ###
