"""Subequipo definition changed

Revision ID: 6c8da6605876
Revises: 64fa2e4ceee0
Create Date: 2025-02-04 13:43:03.286204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c8da6605876'
down_revision = '64fa2e4ceee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subequipo', schema=None) as batch_op:
        batch_op.drop_constraint('id_equipo', type_='foreignkey')
        batch_op.drop_column('id_equipo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subequipo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_equipo', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('id_equipo', 'equipo', ['id_equipo'], ['id_equipo'])

    # ### end Alembic commands ###
