"""Miembro equipo model added

Revision ID: 93de4f73d4b0
Revises: f10126853c00
Create Date: 2025-01-30 09:56:42.716076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93de4f73d4b0'
down_revision = 'f10126853c00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participante')
    with op.batch_alter_table('plantilla', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_miembro', sa.Integer(), nullable=False))
        batch_op.drop_constraint('id_jugador', type_='foreignkey')
        batch_op.create_foreign_key(None, 'miembro_equipo', ['id_miembro'], ['id_miembro'])
        batch_op.drop_column('id_jugador')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantilla', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_jugador', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('id_jugador', 'usuario', ['id_jugador'], ['id_usuario'])
        batch_op.drop_column('id_miembro')

    op.create_table('participante',
    sa.Column('id_participante', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_equipo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_equipo'], ['equipo.id_equipo'], name='id_equipo'),
    sa.PrimaryKeyConstraint('id_participante', name='participante_pkey')
    )
    # ### end Alembic commands ###
