"""Update migratons new

Revision ID: d4651d1ea5ba
Revises: fe7988158178
Create Date: 2025-01-12 01:25:09.431396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4651d1ea5ba'
down_revision = 'fe7988158178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantilla', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_subequipo', sa.Integer(), nullable=False))
        batch_op.drop_constraint('id_equipo', type_='foreignkey')
        batch_op.create_foreign_key(None, 'subequipo', ['id_subequipo'], ['id_subequipo'])
        batch_op.drop_column('id_equipo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantilla', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_equipo', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('id_equipo', 'equipo', ['id_equipo'], ['id_equipo'])
        batch_op.drop_column('id_subequipo')

    # ### end Alembic commands ###
