"""Comentario attriube in request

Revision ID: deb39e718211
Revises: 3597f8f3cff5
Create Date: 2025-01-14 18:43:41.387881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deb39e718211'
down_revision = '3597f8f3cff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comentario_rechazo', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.drop_column('comentario_rechazo')

    # ### end Alembic commands ###
