"""Relation owner and business modified

Revision ID: e5e032eef5ee
Revises: 11c657c85c97
Create Date: 2025-01-20 16:20:31.900593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5e032eef5ee'
down_revision = '11c657c85c97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('establecimiento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_duenio', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('id_duenio', 'duenio', ['id_duenio'], ['id_duenio'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('establecimiento', schema=None) as batch_op:
        batch_op.drop_constraint('id_duenio', type_='foreignkey')
        batch_op.drop_column('id_duenio')

    # ### end Alembic commands ###
