"""Id partido nullable

Revision ID: f10126853c00
Revises: 2b7ea250219f
Create Date: 2025-01-28 09:36:09.315447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f10126853c00'
down_revision = '2b7ea250219f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.drop_column('imagen')
        batch_op.drop_column('descripcion')

    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.alter_column('id_partido',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.alter_column('id_partido',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('imagen', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
