"""Reservante model defined

Revision ID: f77a76d44b7e
Revises: 93de4f73d4b0
Create Date: 2025-01-30 11:33:57.873989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f77a76d44b7e'
down_revision = '93de4f73d4b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_reservante', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('id_reservante', 'reservante', ['id_reservante'], ['id_reservante'])


    tipo_reservante_enum = sa.Enum('usuario', 'equipo', name='tipo_reservante')
    tipo_reservante_enum.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('reservante', schema=None) as batch_op:
        # Convertir la columna de VARCHAR a ENUM
        op.execute(
            "ALTER TABLE reservante ALTER COLUMN tipo_reservante "
            "SET DATA TYPE tipo_reservante USING tipo_reservante::tipo_reservante"
        )

        # Asegurar que la columna tenga el nuevo tipo definido en Alembic
        batch_op.alter_column('tipo_reservante', type_=tipo_reservante_enum, nullable=True)
        # batch_op.alter_column('tipo_reservante',
        #        existing_type=sa.VARCHAR(length=80),
        #        type_=sa.Enum('usuario', 'equipo', name='tipo_reservante'),
        #        nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservante', schema=None) as batch_op:
        batch_op.alter_column('tipo_reservante',
               existing_type=sa.Enum('usuario', 'equipo', name='tipo_reservante'),
               type_=sa.VARCHAR(length=80),
               nullable=False)

    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.drop_constraint('id_reservante', type_='foreignkey')
        batch_op.drop_column('id_reservante')

    # ### end Alembic commands ###
