"""Update migratons new

Revision ID: fe7988158178
Revises: 54eac4cc210c
Create Date: 2025-01-12 01:07:05.011711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe7988158178'
down_revision = '54eac4cc210c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacion_reserva', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_invitado', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('id_partido', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('id_reserva', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('partido', 'partido', ['id_partido'], ['id_partido'])
        batch_op.create_foreign_key('invitado', 'usuario', ['id_invitado'], ['id_usuario'])
        batch_op.create_foreign_key('reserva', 'reserva', ['id_reserva'], ['id_reserva'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacion_reserva', schema=None) as batch_op:
        batch_op.drop_constraint('reserva', type_='foreignkey')
        batch_op.drop_constraint('invitado', type_='foreignkey')
        batch_op.drop_constraint('partido', type_='foreignkey')
        batch_op.drop_column('id_reserva')
        batch_op.drop_column('id_partido')
        batch_op.drop_column('id_invitado')

    # ### end Alembic commands ###
