name: CI Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_NAME: dev-cancheros
  GAR_LOCATION: us-central1
  GCP_REGION: us-central1

jobs:
  deploy:
    name: Deploy to cloud run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Configure Docker
        run: |
          gcloud auth configure-docker '${{ env.GAR_LOCATION }}-docker.pkg.dev'

      - name: Build and push Docker image for canchas service
        run: |
          docker build -t '${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.GAR_NAME }}/dev-canchas-service:${{ github.sha }}' ./
          docker push '${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.GAR_NAME }}/dev-canchas-service:${{ github.sha }}'

      - name: Deploy canchas service to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: dev-canchas-service
          region: ${{ secrets.GCP_REGION }}
          image: "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.GAR_NAME }}/dev-canchas-service:${{ github.sha }}"
          flags: --allow-unauthenticated
  
